//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NasAPI.Resources.ValidationsResources", typeof(ValidationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree the terms.
        /// </summary>
        internal static string AgreedToTerms {
            get {
                return ResourceManager.GetString("AgreedToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Available days.
        /// </summary>
        internal static string Availabledays {
            get {
                return ResourceManager.GetString("Availabledays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the City.
        /// </summary>
        internal static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Code.
        /// </summary>
        internal static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is Required.
        /// </summary>
        internal static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is Required.
        /// </summary>
        internal static string ContactId {
            get {
                return ResourceManager.GetString("ContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Contract Duration.
        /// </summary>
        internal static string ContractDuration {
            get {
                return ResourceManager.GetString("ContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract is Required.
        /// </summary>
        internal static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter District.
        /// </summary>
        internal static string DistrictId {
            get {
                return ResourceManager.GetString("DistrictId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External access token required.
        /// </summary>
        internal static string Externalaccesstoken {
            get {
                return ResourceManager.GetString("Externalaccesstoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Gender.
        /// </summary>
        internal static string GenderId {
            get {
                return ResourceManager.GetString("GenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Iqama Number.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs are Required.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Job Title.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login provider.
        /// </summary>
        internal static string Loginprovider {
            get {
                return ResourceManager.GetString("Loginprovider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the  Nationality.
        /// </summary>
        internal static string NationalityId {
            get {
                return ResourceManager.GetString("NationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqama number Not Valid.
        /// </summary>
        internal static string NotValidIqama {
            get {
                return ResourceManager.GetString("NotValidIqama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number Of hours.
        /// </summary>
        internal static string NumberOfhours {
            get {
                return ResourceManager.GetString("NumberOfhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number Of visits.
        /// </summary>
        internal static string NumberOfvisits {
            get {
                return ResourceManager.GetString("NumberOfvisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number Of workers.
        /// </summary>
        internal static string NumberOfworkers {
            get {
                return ResourceManager.GetString("NumberOfworkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select packages.
        /// </summary>
        internal static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is Required.
        /// </summary>
        internal static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Details is Required.
        /// </summary>
        internal static string ProblemDetails {
            get {
                return ResourceManager.GetString("ProblemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type is Required.
        /// </summary>
        internal static string ProblemTypeId {
            get {
                return ResourceManager.GetString("ProblemTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider key.
        /// </summary>
        internal static string Providerkey {
            get {
                return ResourceManager.GetString("Providerkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Region.
        /// </summary>
        internal static string RegionId {
            get {
                return ResourceManager.GetString("RegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string RegisterComparePassword {
            get {
                return ResourceManager.GetString("RegisterComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is required.
        /// </summary>
        internal static string RegisterFirstNameIsRequired {
            get {
                return ResourceManager.GetString("RegisterFirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is required.
        /// </summary>
        internal static string RegisterLastNameIsRequired {
            get {
                return ResourceManager.GetString("RegisterLastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddleName is required.
        /// </summary>
        internal static string RegisterMiddleNameIsRequired {
            get {
                return ResourceManager.GetString("RegisterMiddleNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName is required.
        /// </summary>
        internal static string RegisterNameIsRequired {
            get {
                return ResourceManager.GetString("RegisterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string RegisterPasswordIsRequired {
            get {
                return ResourceManager.GetString("RegisterPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Phone not valid.
        /// </summary>
        internal static string RegisterPhoneIsNotValed {
            get {
                return ResourceManager.GetString("RegisterPhoneIsNotValed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePhone is required.
        /// </summary>
        internal static string RegisterPhoneIsRequired {
            get {
                return ResourceManager.GetString("RegisterPhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Start day.
        /// </summary>
        internal static string Startday {
            get {
                return ResourceManager.GetString("Startday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Date.
        /// </summary>
        internal static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
    }
}
