//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasAPI.SMSRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSRef.SMSServiceSoap")]
    public interface SMSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSingleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSingleSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSingleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSingleSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendInternationalSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendInternationalSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendInternationalSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendInternationalSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCustomBulkSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendCustomBulkSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage, string VarsList, string ReplacementList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCustomBulkSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendCustomBulkSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage, string VarsList, string ReplacementList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendBulkSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendBulkSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCredit(string strUserName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCreditAsync(string strUserName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsServiceAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsServiceAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsServiceAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsServiceAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCodeDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCodeDescription(string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCodeDescription", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCodeDescriptionAsync(string Code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceSoapChannel : NasAPI.SMSRef.SMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<NasAPI.SMSRef.SMSServiceSoap>, NasAPI.SMSRef.SMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendSingleSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage) {
            return base.Channel.SendSingleSMS(strUserName, strPassword, strTagName, strRecepientNumber, strMessage);
        }
        
        public System.Threading.Tasks.Task<string> SendSingleSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage) {
            return base.Channel.SendSingleSMSAsync(strUserName, strPassword, strTagName, strRecepientNumber, strMessage);
        }
        
        public string SendInternationalSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage) {
            return base.Channel.SendInternationalSMS(strUserName, strPassword, strTagName, strRecepientNumber, strMessage);
        }
        
        public System.Threading.Tasks.Task<string> SendInternationalSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumber, string strMessage) {
            return base.Channel.SendInternationalSMSAsync(strUserName, strPassword, strTagName, strRecepientNumber, strMessage);
        }
        
        public string SendCustomBulkSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage, string VarsList, string ReplacementList) {
            return base.Channel.SendCustomBulkSMS(strUserName, strPassword, strTagName, strRecepientNumbers, strMessage, VarsList, ReplacementList);
        }
        
        public System.Threading.Tasks.Task<string> SendCustomBulkSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage, string VarsList, string ReplacementList) {
            return base.Channel.SendCustomBulkSMSAsync(strUserName, strPassword, strTagName, strRecepientNumbers, strMessage, VarsList, ReplacementList);
        }
        
        public string SendBulkSMS(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage) {
            return base.Channel.SendBulkSMS(strUserName, strPassword, strTagName, strRecepientNumbers, strMessage);
        }
        
        public System.Threading.Tasks.Task<string> SendBulkSMSAsync(string strUserName, string strPassword, string strTagName, string strRecepientNumbers, string strMessage) {
            return base.Channel.SendBulkSMSAsync(strUserName, strPassword, strTagName, strRecepientNumbers, strMessage);
        }
        
        public string GetCredit(string strUserName, string strPassword) {
            return base.Channel.GetCredit(strUserName, strPassword);
        }
        
        public System.Threading.Tasks.Task<string> GetCreditAsync(string strUserName, string strPassword) {
            return base.Channel.GetCreditAsync(strUserName, strPassword);
        }
        
        public bool IsServiceAlive() {
            return base.Channel.IsServiceAlive();
        }
        
        public System.Threading.Tasks.Task<bool> IsServiceAliveAsync() {
            return base.Channel.IsServiceAliveAsync();
        }
        
        public string GetCodeDescription(string Code) {
            return base.Channel.GetCodeDescription(Code);
        }
        
        public System.Threading.Tasks.Task<string> GetCodeDescriptionAsync(string Code) {
            return base.Channel.GetCodeDescriptionAsync(Code);
        }
    }
}
